# DEVELOPMENT
version: '1'
services:
  db:
    container_name: fastback_db
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    restart: unless-stopped
volumes:
  pgdata: